//! cTrader OAuth2 authentication flow.
//!
//! 1. Opens browser to Spotware authorization URL.
//! 2. Runs a tiny local HTTP server to catch the redirect with the auth code.
//! 3. Exchanges the code for access + refresh tokens via Spotware's token endpoint.
//! 4. Connects to cTrader, lists all trading accounts for the token.
//! 5. Returns credentials ready to save.

use std::io::{Read, Write};
use std::net::TcpListener;

use tracing::info;

use crate::client::{CtraderClient, CtraderConfig};
use crate::error::BrokerError;

const SPOTWARE_AUTH_URL: &str = "https://connect.spotware.com/apps/auth";
const SPOTWARE_TOKEN_URL: &str = "https://connect.spotware.com/apps/token";
const CALLBACK_PORT: u16 = 5555;

/// Result of a successful OAuth2 flow.
#[derive(Debug, Clone)]
pub struct AuthResult {
    pub access_token: String,
    pub refresh_token: String,
    pub expires_in: i64,
    pub accounts: Vec<TradingAccount>,
}

/// A cTrader trading account discovered via the access token.
#[derive(Debug, Clone)]
pub struct TradingAccount {
    pub ctid_trader_account_id: u64,
    pub is_live: bool,
    pub trader_login: Option<i64>,
    pub broker_name: Option<String>,
}

/// Saved credentials file content.
#[derive(Debug, Clone)]
pub struct SavedCredentials {
    pub client_id: String,
    pub client_secret: String,
    pub access_token: String,
    pub refresh_token: String,
    pub ctid_account_id: u64,
    pub is_live: bool,
}

/// Run the OAuth2 authorization code flow.
///
/// Opens the browser, waits for the redirect, exchanges the code for tokens.
pub fn run_oauth_flow(client_id: &str, client_secret: &str) -> Result<AuthResult, BrokerError> {
    let redirect_uri = format!("http://localhost:{CALLBACK_PORT}/callback");

    let auth_url = format!(
        "{}?client_id={}&redirect_uri={}&scope=trading",
        SPOTWARE_AUTH_URL,
        urlencoded(client_id),
        urlencoded(&redirect_uri),
    );

    println!();
    println!("Opening browser for cTrader authorization...");
    println!();
    println!("If the browser doesn't open, visit this URL manually:");
    println!("  {auth_url}");
    println!();

    let _ = open_browser(&auth_url);

    let code = wait_for_auth_code()?;
    println!("Authorization code received.");

    println!("Exchanging code for access token...");
    let (access_token, refresh_token, expires_in) =
        exchange_code(&code, client_id, client_secret, &redirect_uri)?;
    info!("Access token obtained (expires in {expires_in}s)");

    println!("Fetching trading accounts...");
    let accounts = list_accounts(client_id, client_secret, &access_token)?;
    info!("Found {} trading account(s)", accounts.len());

    Ok(AuthResult {
        access_token,
        refresh_token,
        expires_in,
        accounts,
    })
}

/// Refresh an existing access token using the refresh token.
pub fn refresh_access_token(
    client_id: &str,
    client_secret: &str,
    refresh_token: &str,
) -> Result<(String, String, i64), BrokerError> {
    let body = format!(
        "grant_type=refresh_token&refresh_token={}&client_id={}&client_secret={}",
        urlencoded(refresh_token),
        urlencoded(client_id),
        urlencoded(client_secret),
    );

    let resp = ureq::post(SPOTWARE_TOKEN_URL)
        .set("Content-Type", "application/x-www-form-urlencoded")
        .send(body.as_bytes())
        .map_err(|e| BrokerError::Connection(format!("Token refresh failed: {e}")))?;

    let json: serde_json::Value = resp
        .into_json()
        .map_err(|e| BrokerError::Protocol(format!("Invalid token response: {e}")))?;

    let access = json["access_token"]
        .as_str()
        .ok_or_else(|| BrokerError::Protocol("Missing access_token in response".into()))?
        .to_string();
    let refresh = json["refresh_token"]
        .as_str()
        .ok_or_else(|| BrokerError::Protocol("Missing refresh_token in response".into()))?
        .to_string();
    let expires = json["expires_in"].as_i64().unwrap_or(0);

    Ok((access, refresh, expires))
}

/// Save credentials to an env file.
pub fn save_credentials(path: &str, creds: &SavedCredentials) -> Result<(), BrokerError> {
    let env_prefix = if creds.is_live {
        "# cTrader Live"
    } else {
        "# cTrader Demo"
    };
    let server = if creds.is_live { "live" } else { "demo" };
    let cid = &creds.client_id;
    let csec = &creds.client_secret;
    let tok = &creds.access_token;
    let rtok = &creds.refresh_token;
    let aid = creds.ctid_account_id;
    let is_demo = !creds.is_live;
    let now = chrono::Utc::now().format("%Y-%m-%d %H:%M UTC");

    let content = format!(
        "{env_prefix} Account \u{2014} GADARAH
# Auto-generated by `gadarah auth` on {now}
# Account: {aid}  |  {server}.ctraderapi.com:5035

GADARAH_CLIENT_ID={cid}
GADARAH_CLIENT_SECRET={csec}
GADARAH_ACCESS_TOKEN={tok}
GADARAH_REFRESH_TOKEN={rtok}
GADARAH_ACCOUNT_ID={aid}
GADARAH_IS_DEMO={is_demo}

# Per-firm aliases (all point to the same account)
GADARAH_FTMO_CLIENT_ID={cid}
GADARAH_FTMO_CLIENT_SECRET={csec}
GADARAH_FTMO_ACCESS_TOKEN={tok}
GADARAH_FTMO_ACCOUNT_ID={aid}
GADARAH_FP_CLIENT_ID={cid}
GADARAH_FP_CLIENT_SECRET={csec}
GADARAH_FP_ACCESS_TOKEN={tok}
GADARAH_FP_ACCOUNT_ID={aid}
GADARAH_THE5ERS_CLIENT_ID={cid}
GADARAH_THE5ERS_CLIENT_SECRET={csec}
GADARAH_THE5ERS_ACCESS_TOKEN={tok}
GADARAH_THE5ERS_ACCOUNT_ID={aid}
GADARAH_ALPHA_CLIENT_ID={cid}
GADARAH_ALPHA_CLIENT_SECRET={csec}
GADARAH_ALPHA_ACCESS_TOKEN={tok}
GADARAH_ALPHA_ACCOUNT_ID={aid}
GADARAH_BG_CLIENT_ID={cid}
GADARAH_BG_CLIENT_SECRET={csec}
GADARAH_BG_ACCESS_TOKEN={tok}
GADARAH_BG_ACCOUNT_ID={aid}
"
    );

    std::fs::write(path, content)
        .map_err(|e| BrokerError::Connection(format!("Failed to write {path}: {e}")))?;
    Ok(())
}

// ── Internal helpers ─────────────────────────────────────────────────────────

fn wait_for_auth_code() -> Result<String, BrokerError> {
    let listener = TcpListener::bind(format!("127.0.0.1:{CALLBACK_PORT}")).map_err(|e| {
        BrokerError::Connection(format!("Failed to bind port {CALLBACK_PORT}: {e}"))
    })?;

    println!(
        "Waiting for authorization on http://localhost:{CALLBACK_PORT}/callback ..."
    );

    let (mut stream, _) = listener
        .accept()
        .map_err(|e| BrokerError::Connection(format!("Accept failed: {e}")))?;

    let mut buf = vec![0u8; 4096];
    let n = stream
        .read(&mut buf)
        .map_err(|e| BrokerError::Connection(format!("Read failed: {e}")))?;
    let request = String::from_utf8_lossy(&buf[..n]);

    // Extract the code from GET /callback?code=XXXX HTTP/1.1
    let code = request
        .lines()
        .next()
        .and_then(|line| line.split_whitespace().nth(1))
        .and_then(|path| {
            path.split('?').nth(1).and_then(|qs| {
                qs.split('&')
                    .find(|p| p.starts_with("code="))
                    .map(|p| p.strip_prefix("code=").unwrap_or("").to_string())
            })
        })
        .ok_or_else(|| BrokerError::AuthFailed("No authorization code in callback".into()))?;

    // Send a success page back to the browser
    let body = concat!(
        "<!DOCTYPE html><html><head><style>",
        "body{background:#0a0e14;color:#c4cad4;font-family:monospace;",
        "display:flex;justify-content:center;align-items:center;height:100vh;margin:0}",
        ".box{text-align:center;border:1px solid #1a3a2a;padding:40px;border-radius:8px;",
        "background:#0d1117}h1{color:#00cc88}",
        "</style></head><body><div class=\"box\">",
        "<h1>GADARAH Authorized</h1>",
        "<p>You can close this tab and return to the terminal.</p>",
        "</div></body></html>"
    );

    let response = format!(
        "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
        body.len(),
        body
    );
    let _ = stream.write_all(response.as_bytes());

    Ok(code)
}

fn exchange_code(
    code: &str,
    client_id: &str,
    client_secret: &str,
    redirect_uri: &str,
) -> Result<(String, String, i64), BrokerError> {
    let body = format!(
        "grant_type=authorization_code&code={}&client_id={}&client_secret={}&redirect_uri={}",
        urlencoded(code),
        urlencoded(client_id),
        urlencoded(client_secret),
        urlencoded(redirect_uri),
    );

    let resp = ureq::post(SPOTWARE_TOKEN_URL)
        .set("Content-Type", "application/x-www-form-urlencoded")
        .send(body.as_bytes())
        .map_err(|e| BrokerError::AuthFailed(format!("Token exchange failed: {e}")))?;

    let json: serde_json::Value = resp
        .into_json()
        .map_err(|e| BrokerError::Protocol(format!("Invalid token response: {e}")))?;

    let access = json["access_token"]
        .as_str()
        .ok_or_else(|| BrokerError::Protocol("Missing access_token".into()))?
        .to_string();
    let refresh = json["refresh_token"]
        .as_str()
        .ok_or_else(|| BrokerError::Protocol("Missing refresh_token".into()))?
        .to_string();
    let expires = json["expires_in"].as_i64().unwrap_or(0);

    Ok((access, refresh, expires))
}

fn list_accounts(
    client_id: &str,
    client_secret: &str,
    access_token: &str,
) -> Result<Vec<TradingAccount>, BrokerError> {
    let config = CtraderConfig::new(client_id.to_string(), client_secret.to_string());
    let mut client = CtraderClient::new(config);
    client.list_accounts_blocking(access_token)
}

/// Minimal URL encoding for form parameters.
fn urlencoded(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for b in s.bytes() {
        match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(b as char)
            }
            _ => {
                out.push('%');
                out.push_str(&format!("{b:02X}"));
            }
        }
    }
    out
}

fn open_browser(url: &str) -> Result<(), std::io::Error> {
    #[cfg(target_os = "linux")]
    {
        std::process::Command::new("xdg-open").arg(url).spawn()?;
    }
    #[cfg(target_os = "macos")]
    {
        std::process::Command::new("open").arg(url).spawn()?;
    }
    #[cfg(target_os = "windows")]
    {
        std::process::Command::new("cmd")
            .args(["/C", "start", "", url])
            .spawn()?;
    }
    Ok(())
}
